# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FlashLapse_CP.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 690)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 670))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../_image/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Image_Frame = QtWidgets.QLabel(self.centralwidget)
        self.Image_Frame.setGeometry(QtCore.QRect(859, 20, 390, 390))
        self.Image_Frame.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.Image_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Image_Frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Image_Frame.setLineWidth(5)
        self.Image_Frame.setText("")
        self.Image_Frame.setPixmap(QtGui.QPixmap("../_image/background.png"))
        self.Image_Frame.setScaledContents(True)
        self.Image_Frame.setObjectName("Image_Frame")
        self.Control_Tab = QtWidgets.QTabWidget(self.centralwidget)
        self.Control_Tab.setGeometry(QtCore.QRect(20, 20, 820, 620))
        self.Control_Tab.setTabPosition(QtWidgets.QTabWidget.North)
        self.Control_Tab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Control_Tab.setObjectName("Control_Tab")
        self.lighting_tab = QtWidgets.QWidget()
        self.lighting_tab.setObjectName("lighting_tab")
        self.frame_2 = QtWidgets.QFrame(self.lighting_tab)
        self.frame_2.setGeometry(QtCore.QRect(640, 20, 151, 301))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 20, 121, 253))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Modes_label = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Modes_label.setObjectName("Modes_label")
        self.verticalLayout_3.addWidget(self.Modes_label)
        self.disco_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.disco_spinBox.setMaximum(1000)
        self.disco_spinBox.setObjectName("disco_spinBox")
        self.verticalLayout_3.addWidget(self.disco_spinBox)
        self.disco_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.disco_pushButton.setEnabled(True)
        self.disco_pushButton.setObjectName("disco_pushButton")
        self.verticalLayout_3.addWidget(self.disco_pushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.rainbow_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.rainbow_spinBox.setMaximum(1000)
        self.rainbow_spinBox.setObjectName("rainbow_spinBox")
        self.verticalLayout_3.addWidget(self.rainbow_spinBox)
        self.rainbow_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.rainbow_pushButton.setEnabled(True)
        self.rainbow_pushButton.setObjectName("rainbow_pushButton")
        self.verticalLayout_3.addWidget(self.rainbow_pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pulse_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.pulse_spinBox.setMaximum(999999)
        self.pulse_spinBox.setObjectName("pulse_spinBox")
        self.verticalLayout_3.addWidget(self.pulse_spinBox)
        self.pulse_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.pulse_pushButton.setEnabled(True)
        self.pulse_pushButton.setObjectName("pulse_pushButton")
        self.verticalLayout_3.addWidget(self.pulse_pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.sundial_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.sundial_spinBox.setMinimum(1)
        self.sundial_spinBox.setMaximum(999)
        self.sundial_spinBox.setObjectName("sundial_spinBox")
        self.verticalLayout_3.addWidget(self.sundial_spinBox)
        self.sundial_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.sundial_pushButton.setEnabled(True)
        self.sundial_pushButton.setObjectName("sundial_pushButton")
        self.verticalLayout_3.addWidget(self.sundial_pushButton)
        self.Ligting_frame = QtWidgets.QFrame(self.lighting_tab)
        self.Ligting_frame.setGeometry(QtCore.QRect(20, 390, 601, 181))
        self.Ligting_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.Ligting_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Ligting_frame.setObjectName("Ligting_frame")
        self.Address_label = QtWidgets.QLabel(self.Ligting_frame)
        self.Address_label.setGeometry(QtCore.QRect(110, 0, 141, 31))
        self.Address_label.setObjectName("Address_label")
        self.color_label = QtWidgets.QLabel(self.Ligting_frame)
        self.color_label.setGeometry(QtCore.QRect(110, 65, 141, 31))
        self.color_label.setObjectName("color_label")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.Ligting_frame)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(20, 19, 561, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.Start_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.Start_label.setObjectName("Start_label")
        self.verticalLayout_18.addWidget(self.Start_label)
        self.Start_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.Start_spinBox.setMinimum(1)
        self.Start_spinBox.setMaximum(85)
        self.Start_spinBox.setObjectName("Start_spinBox")
        self.verticalLayout_18.addWidget(self.Start_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.End_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.End_label.setObjectName("End_label")
        self.verticalLayout_19.addWidget(self.End_label)
        self.End_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.End_spinBox.setMinimum(2)
        self.End_spinBox.setMaximum(86)
        self.End_spinBox.setProperty("value", 86)
        self.End_spinBox.setObjectName("End_spinBox")
        self.verticalLayout_19.addWidget(self.End_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.BRT_lable = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.BRT_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.BRT_lable.setObjectName("BRT_lable")
        self.verticalLayout_20.addWidget(self.BRT_lable)
        self.BRT_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget_4)
        self.BRT_spinBox.setMinimum(1)
        self.BRT_spinBox.setMaximum(150)
        self.BRT_spinBox.setProperty("value", 20)
        self.BRT_spinBox.setObjectName("BRT_spinBox")
        self.verticalLayout_20.addWidget(self.BRT_spinBox)
        self.horizontalLayout_5.addLayout(self.verticalLayout_20)
        self.gridLayoutWidget = QtWidgets.QWidget(self.Ligting_frame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 581, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.B_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.B_spinBox.setMaximum(100)
        self.B_spinBox.setObjectName("B_spinBox")
        self.gridLayout.addWidget(self.B_spinBox, 0, 5, 1, 1)
        self.G_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.G_label.setObjectName("G_label")
        self.gridLayout.addWidget(self.G_label, 0, 2, 1, 1)
        self.R_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.R_spinBox.setMaximum(100)
        self.R_spinBox.setProperty("value", 50)
        self.R_spinBox.setObjectName("R_spinBox")
        self.gridLayout.addWidget(self.R_spinBox, 0, 1, 1, 1)
        self.R_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.R_label.setObjectName("R_label")
        self.gridLayout.addWidget(self.R_label, 0, 0, 1, 1)
        self.W_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.W_label.setObjectName("W_label")
        self.gridLayout.addWidget(self.W_label, 0, 6, 1, 1)
        self.G_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.G_spinBox.setMaximum(100)
        self.G_spinBox.setObjectName("G_spinBox")
        self.gridLayout.addWidget(self.G_spinBox, 0, 3, 1, 1)
        self.B_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.B_label.setObjectName("B_label")
        self.gridLayout.addWidget(self.B_label, 0, 4, 1, 1)
        self.W_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.W_spinBox.setMaximum(100)
        self.W_spinBox.setObjectName("W_spinBox")
        self.gridLayout.addWidget(self.W_spinBox, 0, 7, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Ligting_frame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 130, 171, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lightConfirm_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.lightConfirm_pushButton.setObjectName("lightConfirm_pushButton")
        self.horizontalLayout.addWidget(self.lightConfirm_pushButton)
        self.lightReset_pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.lightReset_pushButton.setObjectName("lightReset_pushButton")
        self.horizontalLayout.addWidget(self.lightReset_pushButton)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.lighting_tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(660, 340, 121, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.powerCycle_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.powerCycle_label.setObjectName("powerCycle_label")
        self.verticalLayout_5.addWidget(self.powerCycle_label)
        self.Cycle_label = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Cycle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Cycle_label.setObjectName("Cycle_label")
        self.verticalLayout_5.addWidget(self.Cycle_label)
        self.powerCycle_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.powerCycle_spinBox.setMinimum(1)
        self.powerCycle_spinBox.setMaximum(999999999)
        self.powerCycle_spinBox.setProperty("value", 60)
        self.powerCycle_spinBox.setObjectName("powerCycle_spinBox")
        self.verticalLayout_5.addWidget(self.powerCycle_spinBox)
        self.confirmCycle_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.confirmCycle_pushButton.setObjectName("confirmCycle_pushButton")
        self.verticalLayout_5.addWidget(self.confirmCycle_pushButton)
        self.IR_pushButton = QtWidgets.QPushButton(self.lighting_tab)
        self.IR_pushButton.setGeometry(QtCore.QRect(650, 520, 141, 51))
        self.IR_pushButton.setObjectName("IR_pushButton")
        self.coreImage = QtWidgets.QLabel(self.lighting_tab)
        self.coreImage.setGeometry(QtCore.QRect(145, 20, 350, 350))
        self.coreImage.setText("")
        self.coreImage.setPixmap(QtGui.QPixmap("../_image/graphics.png"))
        self.coreImage.setScaledContents(True)
        self.coreImage.setObjectName("coreImage")
        self.Control_Tab.addTab(self.lighting_tab, "")
        self.motion_tab = QtWidgets.QWidget()
        self.motion_tab.setObjectName("motion_tab")
        self.motorSpeed_label = QtWidgets.QLabel(self.motion_tab)
        self.motorSpeed_label.setGeometry(QtCore.QRect(430, 540, 121, 31))
        self.motorSpeed_label.setObjectName("motorSpeed_label")
        self.motorSpeed_slider = QtWidgets.QSlider(self.motion_tab)
        self.motorSpeed_slider.setGeometry(QtCore.QRect(20, 540, 381, 32))
        self.motorSpeed_slider.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.motorSpeed_slider.setMinimum(10)
        self.motorSpeed_slider.setMaximum(100)
        self.motorSpeed_slider.setSingleStep(1)
        self.motorSpeed_slider.setPageStep(30)
        self.motorSpeed_slider.setProperty("value", 50)
        self.motorSpeed_slider.setSliderPosition(50)
        self.motorSpeed_slider.setOrientation(QtCore.Qt.Horizontal)
        self.motorSpeed_slider.setInvertedAppearance(False)
        self.motorSpeed_slider.setInvertedControls(True)
        self.motorSpeed_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.motorSpeed_slider.setTickInterval(5)
        self.motorSpeed_slider.setObjectName("motorSpeed_slider")
        self.R1 = QtWidgets.QLabel(self.motion_tab)
        self.R1.setGeometry(QtCore.QRect(720, 100, 60, 60))
        self.R1.setText("")
        self.R1.setPixmap(QtGui.QPixmap("../_image/R1.png"))
        self.R1.setScaledContents(True)
        self.R1.setObjectName("R1")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.motion_tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(630, 80, 81, 51))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.rotate1_label = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.rotate1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotate1_label.setObjectName("rotate1_label")
        self.verticalLayout_11.addWidget(self.rotate1_label)
        self.rotate1_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_6)
        self.rotate1_spinbox.setMinimum(-180)
        self.rotate1_spinbox.setMaximum(180)
        self.rotate1_spinbox.setProperty("value", 10)
        self.rotate1_spinbox.setObjectName("rotate1_spinbox")
        self.verticalLayout_11.addWidget(self.rotate1_spinbox)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.motion_tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(730, 170, 84, 51))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.wait1_label = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.wait1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wait1_label.setObjectName("wait1_label")
        self.verticalLayout_14.addWidget(self.wait1_label)
        self.wait1_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_7)
        self.wait1_spinbox.setMinimum(1)
        self.wait1_spinbox.setMaximum(999999)
        self.wait1_spinbox.setObjectName("wait1_spinbox")
        self.verticalLayout_14.addWidget(self.wait1_spinbox)
        self.R3 = QtWidgets.QLabel(self.motion_tab)
        self.R3.setGeometry(QtCore.QRect(560, 230, 60, 60))
        self.R3.setText("")
        self.R3.setPixmap(QtGui.QPixmap("../_image/L2.png"))
        self.R3.setScaledContents(True)
        self.R3.setObjectName("R3")
        self.R4 = QtWidgets.QLabel(self.motion_tab)
        self.R4.setGeometry(QtCore.QRect(560, 100, 60, 60))
        self.R4.setText("")
        self.R4.setPixmap(QtGui.QPixmap("../_image/L1.png"))
        self.R4.setScaledContents(True)
        self.R4.setObjectName("R4")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.motion_tab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(630, 260, 81, 51))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.rotate2_label = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.rotate2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rotate2_label.setObjectName("rotate2_label")
        self.verticalLayout_15.addWidget(self.rotate2_label)
        self.rotate2_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_8)
        self.rotate2_spinbox.setMinimum(-180)
        self.rotate2_spinbox.setMaximum(180)
        self.rotate2_spinbox.setProperty("value", -10)
        self.rotate2_spinbox.setObjectName("rotate2_spinbox")
        self.verticalLayout_15.addWidget(self.rotate2_spinbox)
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.motion_tab)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(530, 170, 84, 51))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.wait2_label = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.wait2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wait2_label.setObjectName("wait2_label")
        self.verticalLayout_16.addWidget(self.wait2_label)
        self.wait2_spinbox = QtWidgets.QSpinBox(self.verticalLayoutWidget_9)
        self.wait2_spinbox.setMinimum(1)
        self.wait2_spinbox.setMaximum(999999)
        self.wait2_spinbox.setObjectName("wait2_spinbox")
        self.verticalLayout_16.addWidget(self.wait2_spinbox)
        self.R2 = QtWidgets.QLabel(self.motion_tab)
        self.R2.setGeometry(QtCore.QRect(720, 230, 60, 60))
        self.R2.setText("")
        self.R2.setPixmap(QtGui.QPixmap("../_image/R2.png"))
        self.R2.setScaledContents(True)
        self.R2.setObjectName("R2")
        self.frame = QtWidgets.QFrame(self.motion_tab)
        self.frame.setGeometry(QtCore.QRect(20, 20, 491, 501))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphic_2 = QtWidgets.QLabel(self.frame)
        self.graphic_2.setGeometry(QtCore.QRect(45, 50, 400, 400))
        self.graphic_2.setText("")
        self.graphic_2.setPixmap(QtGui.QPixmap("../_image/Scheduler.png"))
        self.graphic_2.setScaledContents(True)
        self.graphic_2.setObjectName("graphic_2")
        self.frame_3 = QtWidgets.QFrame(self.motion_tab)
        self.frame_3.setGeometry(QtCore.QRect(570, 330, 221, 241))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(10, 10, 201, 221))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.schedulerTest_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.schedulerTest_pushButton.setCheckable(False)
        self.schedulerTest_pushButton.setChecked(False)
        self.schedulerTest_pushButton.setObjectName("schedulerTest_pushButton")
        self.verticalLayout_17.addWidget(self.schedulerTest_pushButton)
        self.schedulerSet_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.schedulerSet_pushButton.setObjectName("schedulerSet_pushButton")
        self.verticalLayout_17.addWidget(self.schedulerSet_pushButton)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem4)
        self.clinostatSet_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.clinostatSet_pushButton.setObjectName("clinostatSet_pushButton")
        self.verticalLayout_22.addWidget(self.clinostatSet_pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_22.addItem(spacerItem5)
        self.motor_label = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.motor_label.setObjectName("motor_label")
        self.verticalLayout_22.addWidget(self.motor_label)
        self.motor_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_10)
        self.motor_spinBox.setMinimum(-180)
        self.motor_spinBox.setMaximum(180)
        self.motor_spinBox.setProperty("value", 90)
        self.motor_spinBox.setObjectName("motor_spinBox")
        self.verticalLayout_22.addWidget(self.motor_spinBox)
        self.motorConfirm_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_10)
        self.motorConfirm_pushButton.setObjectName("motorConfirm_pushButton")
        self.verticalLayout_22.addWidget(self.motorConfirm_pushButton)
        self.verticalLayout_17.addLayout(self.verticalLayout_22)
        self.Control_Tab.addTab(self.motion_tab, "")
        self.preset_tab = QtWidgets.QWidget()
        self.preset_tab.setObjectName("preset_tab")
        self.lightingPreset_tabWidget = QtWidgets.QTabWidget(self.preset_tab)
        self.lightingPreset_tabWidget.setEnabled(False)
        self.lightingPreset_tabWidget.setGeometry(QtCore.QRect(20, 50, 371, 391))
        self.lightingPreset_tabWidget.setObjectName("lightingPreset_tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.Germination_textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.Germination_textBrowser.setGeometry(QtCore.QRect(20, 20, 321, 171))
        self.Germination_textBrowser.setObjectName("Germination_textBrowser")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 250, 321, 61))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.germinationColor_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.germinationColor_comboBox.setObjectName("germinationColor_comboBox")
        self.germinationColor_comboBox.addItem("")
        self.germinationColor_comboBox.addItem("")
        self.germinationColor_comboBox.addItem("")
        self.germinationColor_comboBox.addItem("")
        self.germinationColor_comboBox.addItem("")
        self.germinationColor_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.germinationColor_comboBox, 0, 1, 1, 1)
        self.germinationColor_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.germinationColor_label.setObjectName("germinationColor_label")
        self.gridLayout_3.addWidget(self.germinationColor_label, 0, 0, 1, 1)
        self.germinationDirection_label = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.germinationDirection_label.setObjectName("germinationDirection_label")
        self.gridLayout_3.addWidget(self.germinationDirection_label, 1, 0, 1, 1)
        self.germinationDirection_comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_3)
        self.germinationDirection_comboBox.setObjectName("germinationDirection_comboBox")
        self.germinationDirection_comboBox.addItem("")
        self.germinationDirection_comboBox.addItem("")
        self.germinationDirection_comboBox.addItem("")
        self.germinationDirection_comboBox.addItem("")
        self.germinationDirection_comboBox.addItem("")
        self.germinationDirection_comboBox.addItem("")
        self.germinationDirection_comboBox.addItem("")
        self.germinationDirection_comboBox.addItem("")
        self.gridLayout_3.addWidget(self.germinationDirection_comboBox, 1, 1, 1, 1)
        self.lightingPreset_tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.Germination_textBrowser_3 = QtWidgets.QTextBrowser(self.tab_2)
        self.Germination_textBrowser_3.setGeometry(QtCore.QRect(20, 20, 321, 171))
        self.Germination_textBrowser_3.setObjectName("Germination_textBrowser_3")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 250, 321, 61))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cycleTime_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.cycleTime_label.setObjectName("cycleTime_label")
        self.gridLayout_4.addWidget(self.cycleTime_label, 0, 0, 1, 1)
        self.stripLength_label = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.stripLength_label.setObjectName("stripLength_label")
        self.gridLayout_4.addWidget(self.stripLength_label, 1, 0, 1, 1)
        self.cycleTime_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.cycleTime_spinBox.setMinimum(1)
        self.cycleTime_spinBox.setMaximum(999)
        self.cycleTime_spinBox.setProperty("value", 24)
        self.cycleTime_spinBox.setObjectName("cycleTime_spinBox")
        self.gridLayout_4.addWidget(self.cycleTime_spinBox, 0, 1, 1, 1)
        self.stripLength_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.stripLength_spinBox.setMinimum(1)
        self.stripLength_spinBox.setMaximum(15)
        self.stripLength_spinBox.setProperty("value", 3)
        self.stripLength_spinBox.setObjectName("stripLength_spinBox")
        self.gridLayout_4.addWidget(self.stripLength_spinBox, 1, 1, 1, 1)
        self.lightingPreset_tabWidget.addTab(self.tab_2, "")
        self.motionPreset_tabWidget = QtWidgets.QTabWidget(self.preset_tab)
        self.motionPreset_tabWidget.setEnabled(False)
        self.motionPreset_tabWidget.setGeometry(QtCore.QRect(420, 50, 371, 391))
        self.motionPreset_tabWidget.setObjectName("motionPreset_tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gravitropism_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.gravitropism_textBrowser.setGeometry(QtCore.QRect(20, 20, 321, 171))
        self.gravitropism_textBrowser.setObjectName("gravitropism_textBrowser")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 250, 321, 61))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.rotateAfter_label = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.rotateAfter_label.setObjectName("rotateAfter_label")
        self.gridLayout_5.addWidget(self.rotateAfter_label, 0, 0, 1, 1)
        self.gravitropism_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.gravitropism_spinBox.setMinimum(1)
        self.gravitropism_spinBox.setMaximum(999)
        self.gravitropism_spinBox.setProperty("value", 120)
        self.gravitropism_spinBox.setObjectName("gravitropism_spinBox")
        self.gridLayout_5.addWidget(self.gravitropism_spinBox, 0, 1, 1, 1)
        self.motionPreset_tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(20, 250, 321, 61))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.rotateDelay_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.rotateDelay_label.setObjectName("rotateDelay_label")
        self.gridLayout_6.addWidget(self.rotateDelay_label, 1, 0, 1, 1)
        self.rotateDelay_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.rotateDelay_spinBox.setMinimum(1)
        self.rotateDelay_spinBox.setMaximum(999)
        self.rotateDelay_spinBox.setProperty("value", 120)
        self.rotateDelay_spinBox.setObjectName("rotateDelay_spinBox")
        self.gridLayout_6.addWidget(self.rotateDelay_spinBox, 1, 1, 1, 1)
        self.rotateAmount_label = QtWidgets.QLabel(self.gridLayoutWidget_6)
        self.rotateAmount_label.setObjectName("rotateAmount_label")
        self.gridLayout_6.addWidget(self.rotateAmount_label, 0, 0, 1, 1)
        self.rotateAmount_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_6)
        self.rotateAmount_spinBox.setMinimum(-180)
        self.rotateAmount_spinBox.setMaximum(180)
        self.rotateAmount_spinBox.setProperty("value", 90)
        self.rotateAmount_spinBox.setObjectName("rotateAmount_spinBox")
        self.gridLayout_6.addWidget(self.rotateAmount_spinBox, 0, 1, 1, 1)
        self.Germination_textBrowser_4 = QtWidgets.QTextBrowser(self.tab_4)
        self.Germination_textBrowser_4.setGeometry(QtCore.QRect(20, 20, 321, 171))
        self.Germination_textBrowser_4.setObjectName("Germination_textBrowser_4")
        self.motionPreset_tabWidget.addTab(self.tab_4, "")
        self.lightingPS_label = QtWidgets.QLabel(self.preset_tab)
        self.lightingPS_label.setGeometry(QtCore.QRect(140, 30, 121, 20))
        self.lightingPS_label.setObjectName("lightingPS_label")
        self.MotorPS_label = QtWidgets.QLabel(self.preset_tab)
        self.MotorPS_label.setGeometry(QtCore.QRect(540, 30, 121, 20))
        self.MotorPS_label.setObjectName("MotorPS_label")
        self.lightingPreset_pushButton = QtWidgets.QPushButton(self.preset_tab)
        self.lightingPreset_pushButton.setEnabled(False)
        self.lightingPreset_pushButton.setGeometry(QtCore.QRect(130, 500, 151, 41))
        self.lightingPreset_pushButton.setObjectName("lightingPreset_pushButton")
        self.MotionPreset_pushButton = QtWidgets.QPushButton(self.preset_tab)
        self.MotionPreset_pushButton.setEnabled(False)
        self.MotionPreset_pushButton.setGeometry(QtCore.QRect(530, 500, 151, 41))
        self.MotionPreset_pushButton.setObjectName("MotionPreset_pushButton")
        self.Control_Tab.addTab(self.preset_tab, "")
        self.imaging_tab = QtWidgets.QWidget()
        self.imaging_tab.setObjectName("imaging_tab")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.imaging_tab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 420, 422, 54))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.CoreCtr_label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.CoreCtr_label_6.setObjectName("CoreCtr_label_6")
        self.gridLayout_2.addWidget(self.CoreCtr_label_6, 1, 1, 1, 1)
        self.x_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.x_resolution_spinBox.setMinimum(50)
        self.x_resolution_spinBox.setMaximum(3240)
        self.x_resolution_spinBox.setProperty("value", 2464)
        self.x_resolution_spinBox.setObjectName("x_resolution_spinBox")
        self.gridLayout_2.addWidget(self.x_resolution_spinBox, 0, 0, 1, 1)
        self.xRange_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.xRange_label.setAlignment(QtCore.Qt.AlignCenter)
        self.xRange_label.setObjectName("xRange_label")
        self.gridLayout_2.addWidget(self.xRange_label, 1, 0, 1, 1)
        self.y_resolution_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.y_resolution_spinBox.setMinimum(50)
        self.y_resolution_spinBox.setMaximum(2464)
        self.y_resolution_spinBox.setProperty("value", 2464)
        self.y_resolution_spinBox.setObjectName("y_resolution_spinBox")
        self.gridLayout_2.addWidget(self.y_resolution_spinBox, 0, 2, 1, 1)
        self.x_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.x_label.setObjectName("x_label")
        self.gridLayout_2.addWidget(self.x_label, 0, 1, 1, 1)
        self.yRange_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.yRange_label.setAlignment(QtCore.Qt.AlignCenter)
        self.yRange_label.setObjectName("yRange_label")
        self.gridLayout_2.addWidget(self.yRange_label, 1, 2, 1, 1)
        self.resolution_label = QtWidgets.QLabel(self.imaging_tab)
        self.resolution_label.setGeometry(QtCore.QRect(100, 390, 231, 31))
        self.resolution_label.setObjectName("resolution_label")
        self.format_label = QtWidgets.QLabel(self.imaging_tab)
        self.format_label.setGeometry(QtCore.QRect(560, 390, 201, 31))
        self.format_label.setObjectName("format_label")
        self.layoutWidget = QtWidgets.QWidget(self.imaging_tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 500, 771, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Progress_Label = QtWidgets.QLabel(self.layoutWidget)
        self.Progress_Label.setObjectName("Progress_Label")
        self.verticalLayout_7.addWidget(self.Progress_Label, 0, QtCore.Qt.AlignHCenter)
        self.Progress_Bar = QtWidgets.QProgressBar(self.layoutWidget)
        self.Progress_Bar.setEnabled(False)
        self.Progress_Bar.setProperty("value", 0)
        self.Progress_Bar.setObjectName("Progress_Bar")
        self.verticalLayout_7.addWidget(self.Progress_Bar)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.imaging_tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(560, 420, 201, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.JPG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.JPG_radioButton.setChecked(True)
        self.JPG_radioButton.setObjectName("JPG_radioButton")
        self.horizontalLayout_7.addWidget(self.JPG_radioButton)
        self.PNG_radioButton = QtWidgets.QRadioButton(self.horizontalLayoutWidget_6)
        self.PNG_radioButton.setEnabled(True)
        self.PNG_radioButton.setObjectName("PNG_radioButton")
        self.horizontalLayout_7.addWidget(self.PNG_radioButton)
        self.storage_tabWidget = QtWidgets.QTabWidget(self.imaging_tab)
        self.storage_tabWidget.setGeometry(QtCore.QRect(20, 230, 771, 161))
        self.storage_tabWidget.setObjectName("storage_tabWidget")
        self.local_tab = QtWidgets.QWidget()
        self.local_tab.setObjectName("local_tab")
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.local_tab)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(20, 10, 721, 111))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.directory_label = QtWidgets.QLabel(self.verticalLayoutWidget_13)
        self.directory_label.setEnabled(True)
        self.directory_label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.directory_label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.directory_label.setAlignment(QtCore.Qt.AlignCenter)
        self.directory_label.setObjectName("directory_label")
        self.verticalLayout_9.addWidget(self.directory_label)
        self.directory_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_13)
        self.directory_pushButton.setEnabled(True)
        self.directory_pushButton.setCheckable(False)
        self.directory_pushButton.setObjectName("directory_pushButton")
        self.verticalLayout_9.addWidget(self.directory_pushButton)
        self.storage_tabWidget.addTab(self.local_tab, "")
        self.cloud_tab = QtWidgets.QWidget()
        self.cloud_tab.setObjectName("cloud_tab")
        self.Cyverse_frame = QtWidgets.QFrame(self.cloud_tab)
        self.Cyverse_frame.setGeometry(QtCore.QRect(9, 9, 741, 121))
        self.Cyverse_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Cyverse_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Cyverse_frame.setObjectName("Cyverse_frame")
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.Cyverse_frame)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 0, 721, 121))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cyverseUsername_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.cyverseUsername_lineEdit.setEnabled(True)
        self.cyverseUsername_lineEdit.setObjectName("cyverseUsername_lineEdit")
        self.verticalLayout_4.addWidget(self.cyverseUsername_lineEdit)
        self.cyversePassword_lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.cyversePassword_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.cyversePassword_lineEdit.setClearButtonEnabled(True)
        self.cyversePassword_lineEdit.setObjectName("cyversePassword_lineEdit")
        self.verticalLayout_4.addWidget(self.cyversePassword_lineEdit)
        self.cyverseConfirm_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_11)
        self.cyverseConfirm_pushButton.setAutoRepeatDelay(300)
        self.cyverseConfirm_pushButton.setDefault(False)
        self.cyverseConfirm_pushButton.setObjectName("cyverseConfirm_pushButton")
        self.verticalLayout_4.addWidget(self.cyverseConfirm_pushButton)
        self.cyverseDefault_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_11)
        self.cyverseDefault_pushButton.setObjectName("cyverseDefault_pushButton")
        self.verticalLayout_4.addWidget(self.cyverseDefault_pushButton)
        self.storage_tabWidget.addTab(self.cloud_tab, "")
        self.layoutWidget1 = QtWidgets.QWidget(self.imaging_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 771, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.imageTitle_label = QtWidgets.QLabel(self.layoutWidget1)
        self.imageTitle_label.setObjectName("imageTitle_label")
        self.verticalLayout.addWidget(self.imageTitle_label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.imageTitle_lineEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.imageTitle_lineEdit.setEnabled(True)
        self.imageTitle_lineEdit.setObjectName("imageTitle_lineEdit")
        self.horizontalLayout_2.addWidget(self.imageTitle_lineEdit)
        self.addDate_pushButton = QtWidgets.QPushButton(self.layoutWidget1)
        self.addDate_pushButton.setEnabled(False)
        self.addDate_pushButton.setObjectName("addDate_pushButton")
        self.horizontalLayout_2.addWidget(self.addDate_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.ImageInterval_label = QtWidgets.QLabel(self.layoutWidget1)
        self.ImageInterval_label.setObjectName("ImageInterval_label")
        self.verticalLayout.addWidget(self.ImageInterval_label)
        self.ImageInterval_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.ImageInterval_spinBox.setEnabled(True)
        self.ImageInterval_spinBox.setMinimum(1)
        self.ImageInterval_spinBox.setMaximum(99999999)
        self.ImageInterval_spinBox.setProperty("value", 10)
        self.ImageInterval_spinBox.setObjectName("ImageInterval_spinBox")
        self.verticalLayout.addWidget(self.ImageInterval_spinBox)
        spacerItem7 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.imageDuration_label = QtWidgets.QLabel(self.layoutWidget1)
        self.imageDuration_label.setObjectName("imageDuration_label")
        self.verticalLayout.addWidget(self.imageDuration_label)
        self.imageDuration_spinBox = QtWidgets.QSpinBox(self.layoutWidget1)
        self.imageDuration_spinBox.setEnabled(True)
        self.imageDuration_spinBox.setMinimum(1)
        self.imageDuration_spinBox.setMaximum(99999999)
        self.imageDuration_spinBox.setObjectName("imageDuration_spinBox")
        self.verticalLayout.addWidget(self.imageDuration_spinBox)
        self.line = QtWidgets.QFrame(self.imaging_tab)
        self.line.setGeometry(QtCore.QRect(40, 480, 721, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.Control_Tab.addTab(self.imaging_tab, "")
        self.Misc_Frame = QtWidgets.QFrame(self.centralwidget)
        self.Misc_Frame.setGeometry(QtCore.QRect(849, 420, 411, 220))
        self.Misc_Frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Misc_Frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Misc_Frame.setObjectName("Misc_Frame")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.Misc_Frame)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(240, 10, 161, 114))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.snapshot_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.snapshot_pushButton.setEnabled(True)
        self.snapshot_pushButton.setObjectName("snapshot_pushButton")
        self.verticalLayout_13.addWidget(self.snapshot_pushButton)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.liveFeed_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.liveFeed_pushButton.setObjectName("liveFeed_pushButton")
        self.horizontalLayout_6.addWidget(self.liveFeed_pushButton)
        self.liveFeed_spinBox = QtWidgets.QSpinBox(self.verticalLayoutWidget_5)
        self.liveFeed_spinBox.setMinimum(1)
        self.liveFeed_spinBox.setMaximum(600)
        self.liveFeed_spinBox.setObjectName("liveFeed_spinBox")
        self.horizontalLayout_6.addWidget(self.liveFeed_spinBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_6)
        self.preview_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.preview_pushButton.setEnabled(True)
        self.preview_pushButton.setObjectName("preview_pushButton")
        self.verticalLayout_13.addWidget(self.preview_pushButton)
        self.rotate_pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.rotate_pushButton.setObjectName("rotate_pushButton")
        self.verticalLayout_13.addWidget(self.rotate_pushButton)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.Misc_Frame)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(13, 10, 211, 129))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.AOI_label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.AOI_label_3.setObjectName("AOI_label_3")
        self.verticalLayout_12.addWidget(self.AOI_label_3)
        self.xAxis_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.xAxis_label.setObjectName("xAxis_label")
        self.verticalLayout_12.addWidget(self.xAxis_label)
        self.xAxis_horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.xAxis_horizontalSlider.setMaximum(100)
        self.xAxis_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xAxis_horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.xAxis_horizontalSlider.setObjectName("xAxis_horizontalSlider")
        self.verticalLayout_12.addWidget(self.xAxis_horizontalSlider)
        self.yAxis_label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.yAxis_label.setObjectName("yAxis_label")
        self.verticalLayout_12.addWidget(self.yAxis_label)
        self.yAxis_horizontalSlider = QtWidgets.QSlider(self.verticalLayoutWidget_4)
        self.yAxis_horizontalSlider.setMinimum(1)
        self.yAxis_horizontalSlider.setMaximum(100)
        self.yAxis_horizontalSlider.setProperty("value", 100)
        self.yAxis_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yAxis_horizontalSlider.setInvertedAppearance(True)
        self.yAxis_horizontalSlider.setInvertedControls(False)
        self.yAxis_horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.yAxis_horizontalSlider.setObjectName("yAxis_horizontalSlider")
        self.verticalLayout_12.addWidget(self.yAxis_horizontalSlider)
        self.startRoutines_pushButton = QtWidgets.QPushButton(self.Misc_Frame)
        self.startRoutines_pushButton.setEnabled(False)
        self.startRoutines_pushButton.setGeometry(QtCore.QRect(230, 140, 171, 71))
        self.startRoutines_pushButton.setObjectName("startRoutines_pushButton")
        self.frame_4 = QtWidgets.QFrame(self.Misc_Frame)
        self.frame_4.setGeometry(QtCore.QRect(9, 130, 211, 81))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.frame_4)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 191, 61))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.temperatureData_label = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.temperatureData_label.setObjectName("temperatureData_label")
        self.gridLayout_7.addWidget(self.temperatureData_label, 0, 0, 1, 1)
        self.humidityData_label = QtWidgets.QLabel(self.gridLayoutWidget_7)
        self.humidityData_label.setObjectName("humidityData_label")
        self.gridLayout_7.addWidget(self.humidityData_label, 1, 0, 1, 1)
        self.sample_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_7)
        self.sample_spinBox.setPrefix("")
        self.sample_spinBox.setMinimum(1)
        self.sample_spinBox.setMaximum(120000)
        self.sample_spinBox.setObjectName("sample_spinBox")
        self.gridLayout_7.addWidget(self.sample_spinBox, 0, 1, 1, 1)
        self.log_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_7)
        self.log_pushButton.setObjectName("log_pushButton")
        self.gridLayout_7.addWidget(self.log_pushButton, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionOpen_Directory = QtWidgets.QAction(MainWindow)
        self.actionOpen_Directory.setEnabled(False)
        self.actionOpen_Directory.setObjectName("actionOpen_Directory")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCreate_Timelapse = QtWidgets.QAction(MainWindow)
        self.actionCreate_Timelapse.setObjectName("actionCreate_Timelapse")

        self.retranslateUi(MainWindow)
        self.Control_Tab.setCurrentIndex(0)
        self.lightingPreset_tabWidget.setCurrentIndex(0)
        self.motionPreset_tabWidget.setCurrentIndex(0)
        self.storage_tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FlashLapse Commad Point"))
        self.Modes_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Demos</span></p></body></html>"))
        self.disco_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.disco_pushButton.setText(_translate("MainWindow", "Disco"))
        self.rainbow_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.rainbow_pushButton.setText(_translate("MainWindow", "Rainbow"))
        self.pulse_spinBox.setSuffix(_translate("MainWindow", " ms"))
        self.pulse_pushButton.setText(_translate("MainWindow", "Pluse"))
        self.sundial_spinBox.setSuffix(_translate("MainWindow", " s"))
        self.sundial_pushButton.setText(_translate("MainWindow", "Sundial"))
        self.Address_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">LED Address</span></p></body></html>"))
        self.color_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Color Setting</span></p></body></html>"))
        self.Start_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Start LED:</span></p></body></html>"))
        self.Start_spinBox.setSuffix(_translate("MainWindow", " [1 , 85]"))
        self.Start_spinBox.setPrefix(_translate("MainWindow", "# "))
        self.End_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">End LED:</span></p></body></html>"))
        self.End_spinBox.setSuffix(_translate("MainWindow", " [2 , 86]"))
        self.End_spinBox.setPrefix(_translate("MainWindow", "# "))
        self.BRT_lable.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Brightness:</span></p></body></html>"))
        self.BRT_spinBox.setSuffix(_translate("MainWindow", " % [0 , 150]"))
        self.B_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.G_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Green:</span></p></body></html>"))
        self.R_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.R_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Red:</span></p></body></html>"))
        self.W_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">White:</span></p></body></html>"))
        self.G_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.B_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Blue:</span></p></body></html>"))
        self.W_spinBox.setSuffix(_translate("MainWindow", " %"))
        self.lightConfirm_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.lightReset_pushButton.setText(_translate("MainWindow", "RESET"))
        self.powerCycle_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Power Cycle</span></p></body></html>"))
        self.Cycle_label.setText(_translate("MainWindow", "Cycle Duration:"))
        self.powerCycle_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.confirmCycle_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.IR_pushButton.setText(_translate("MainWindow", "IR STATUS:OFF"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.lighting_tab), _translate("MainWindow", "Lighting"))
        self.motorSpeed_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Motor RPM: 5.0</p></body></html>"))
        self.rotate1_label.setText(_translate("MainWindow", "Rotate"))
        self.rotate1_spinbox.setSuffix(_translate("MainWindow", " °"))
        self.wait1_label.setText(_translate("MainWindow", "Pause For"))
        self.wait1_spinbox.setSuffix(_translate("MainWindow", " min"))
        self.rotate2_label.setText(_translate("MainWindow", "Rotate"))
        self.rotate2_spinbox.setSuffix(_translate("MainWindow", " °"))
        self.wait2_label.setText(_translate("MainWindow", "Pause For"))
        self.wait2_spinbox.setSuffix(_translate("MainWindow", " min"))
        self.schedulerTest_pushButton.setText(_translate("MainWindow", "Test Cycle"))
        self.schedulerSet_pushButton.setText(_translate("MainWindow", "Set Cycle"))
        self.clinostatSet_pushButton.setText(_translate("MainWindow", "Run Clinostat"))
        self.motor_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Rotate Motor</span></p></body></html>"))
        self.motor_spinBox.setSuffix(_translate("MainWindow", " °"))
        self.motorConfirm_pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.motion_tab), _translate("MainWindow", "Motion"))
        self.Germination_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">Germination Assay</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">The seeds are allowed to germinate for five days under 80% brightness, solid color growth lights, lighting direction and color can be customized by the user.</span></p></body></html>"))
        self.germinationColor_comboBox.setItemText(0, _translate("MainWindow", "RED"))
        self.germinationColor_comboBox.setItemText(1, _translate("MainWindow", "GREEN"))
        self.germinationColor_comboBox.setItemText(2, _translate("MainWindow", "BLUE"))
        self.germinationColor_comboBox.setItemText(3, _translate("MainWindow", "PURPLE"))
        self.germinationColor_comboBox.setItemText(4, _translate("MainWindow", "RGB WHITE"))
        self.germinationColor_comboBox.setItemText(5, _translate("MainWindow", "WARM WHITE"))
        self.germinationColor_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Color</span></p></body></html>"))
        self.germinationDirection_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Direction</span></p></body></html>"))
        self.germinationDirection_comboBox.setItemText(0, _translate("MainWindow", "FULL"))
        self.germinationDirection_comboBox.setItemText(1, _translate("MainWindow", "TOP"))
        self.germinationDirection_comboBox.setItemText(2, _translate("MainWindow", "BOTTOM"))
        self.germinationDirection_comboBox.setItemText(3, _translate("MainWindow", "LEFT"))
        self.germinationDirection_comboBox.setItemText(4, _translate("MainWindow", "RIGHT"))
        self.germinationDirection_comboBox.setItemText(5, _translate("MainWindow", "TOP THIRD"))
        self.germinationDirection_comboBox.setItemText(6, _translate("MainWindow", "LEFT THIRD"))
        self.germinationDirection_comboBox.setItemText(7, _translate("MainWindow", "RIGHT THIRD"))
        self.lightingPreset_tabWidget.setTabText(self.lightingPreset_tabWidget.indexOf(self.tab), _translate("MainWindow", "Germination"))
        self.Germination_textBrowser_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">Sun Light Cycle</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">The seeds are allowed to germinate for five days under 50% brightness, rotating set of cool white growth lights, the time per cycle and the length of the light strip can be customized by the user.</span></p></body></html>"))
        self.cycleTime_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Cycle Time</span></p></body></html>"))
        self.stripLength_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Strip Length</span></p></body></html>"))
        self.cycleTime_spinBox.setSuffix(_translate("MainWindow", " h"))
        self.stripLength_spinBox.setSuffix(_translate("MainWindow", " pix"))
        self.lightingPreset_tabWidget.setTabText(self.lightingPreset_tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Sun Cycle"))
        self.gravitropism_textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">Gravitropism Assay</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">The seeds are allowed to germinate for four days under 100% brightness, cool white growth lights, lighting direction is set to top half. After a time specified by the user, a 90 degrees rotation occurs, and lighting direction is set to right half.</span></p></body></html>"))
        self.rotateAfter_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Rotate After</span></p></body></html>"))
        self.gravitropism_spinBox.setSuffix(_translate("MainWindow", " h"))
        self.motionPreset_tabWidget.setTabText(self.motionPreset_tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Gravitropism"))
        self.rotateDelay_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Rotate Delay</span></p></body></html>"))
        self.rotateDelay_spinBox.setSuffix(_translate("MainWindow", " h"))
        self.rotateAmount_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Rotate Amount</span></p></body></html>"))
        self.rotateAmount_spinBox.setSuffix(_translate("MainWindow", " °"))
        self.Germination_textBrowser_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:600;\">Rotate Timer</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Rotate user-specified amount after a user-specified delay.</span></p></body></html>"))
        self.motionPreset_tabWidget.setTabText(self.motionPreset_tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Rotate Timer"))
        self.lightingPS_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Lighting Presets</span></p></body></html>"))
        self.MotorPS_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Motion Presets</span></p></body></html>"))
        self.lightingPreset_pushButton.setText(_translate("MainWindow", "Toggle Lighting Preset"))
        self.MotionPreset_pushButton.setText(_translate("MainWindow", "Toggle Lighting Preset"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.preset_tab), _translate("MainWindow", "Preset"))
        self.CoreCtr_label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.x_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.xRange_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 3240 ]</span></p></body></html>"))
        self.y_resolution_spinBox.setSuffix(_translate("MainWindow", " px"))
        self.x_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">X</p></body></html>"))
        self.yRange_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; color:#000000;\">[ 50 , 2464 ]</span></p></body></html>"))
        self.resolution_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGING RESOLUTION</span></p></body></html>"))
        self.format_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">IMAGE FORMAT</span></p></body></html>"))
        self.Progress_Label.setText(_translate("MainWindow", "Progress: 0 / 6"))
        self.JPG_radioButton.setText(_translate("MainWindow", ".JPG"))
        self.PNG_radioButton.setText(_translate("MainWindow", ".PNG"))
        self.directory_label.setText(_translate("MainWindow", "Sequence Title Required"))
        self.directory_pushButton.setText(_translate("MainWindow", "Change Storage Directory"))
        self.storage_tabWidget.setTabText(self.storage_tabWidget.indexOf(self.local_tab), _translate("MainWindow", "Local"))
        self.cyverseUsername_lineEdit.setPlaceholderText(_translate("MainWindow", "Cyverse Username"))
        self.cyversePassword_lineEdit.setPlaceholderText(_translate("MainWindow", "Cyverse Password"))
        self.cyverseConfirm_pushButton.setText(_translate("MainWindow", "Authenticate CyVerse Credentials"))
        self.cyverseDefault_pushButton.setText(_translate("MainWindow", "Save As Default"))
        self.storage_tabWidget.setTabText(self.storage_tabWidget.indexOf(self.cloud_tab), _translate("MainWindow", "CyVerse"))
        self.imageTitle_label.setText(_translate("MainWindow", "Image Sequence Title:"))
        self.addDate_pushButton.setText(_translate("MainWindow", "Add Date"))
        self.ImageInterval_label.setText(_translate("MainWindow", "Image Capture Interval:"))
        self.ImageInterval_spinBox.setSuffix(_translate("MainWindow", " s"))
        self.imageDuration_label.setText(_translate("MainWindow", "Image Sequence Duration:"))
        self.imageDuration_spinBox.setSuffix(_translate("MainWindow", " min"))
        self.Control_Tab.setTabText(self.Control_Tab.indexOf(self.imaging_tab), _translate("MainWindow", "Imaging"))
        self.snapshot_pushButton.setText(_translate("MainWindow", "Snapshot"))
        self.liveFeed_pushButton.setText(_translate("MainWindow", "Live Feed"))
        self.liveFeed_spinBox.setSuffix(_translate("MainWindow", " s"))
        self.preview_pushButton.setText(_translate("MainWindow", "Full Preview"))
        self.rotate_pushButton.setText(_translate("MainWindow", "Rotate Image"))
        self.AOI_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Zoom Control</span></p></body></html>"))
        self.xAxis_label.setText(_translate("MainWindow", "AXIS A: 0.0"))
        self.yAxis_label.setText(_translate("MainWindow", "AXIS B: 1.0"))
        self.startRoutines_pushButton.setText(_translate("MainWindow", "Start LOCAL Sequence"))
        self.temperatureData_label.setText(_translate("MainWindow", "NO_DATA"))
        self.humidityData_label.setText(_translate("MainWindow", "NO_DATA"))
        self.sample_spinBox.setSuffix(_translate("MainWindow", "s /sample"))
        self.log_pushButton.setText(_translate("MainWindow", "START LOG"))
        self.actionOpen_Directory.setText(_translate("MainWindow", "Open Directory"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionCreate_Timelapse.setText(_translate("MainWindow", "Create Timelapse"))
